# Generated by Django 5.1.4 on 2025-04-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='space/images')),
            ],
        ),
        migrations.AlterField(
            model_name='celestialbodies',
            name='image',
            field=models.ImageField(default='', upload_to='space/images'),
        ),
    ]
