# Generated by Django 5.1.4 on 2025-04-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_blogs_alter_celestialbodies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
